#!/usr/bin/env python3

# Copyright 2022 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import

import sys

from sr_gui_fingertip_visualization.sr_gui_fingertip_visualization import SrFingertipVisualizer
from rqt_gui.main import Main


plugin = 'sr_gui_fingertip_visualization.sr_gui_fingertip_visualization.SrFingertipVisualizer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
